name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          pip install pytest mypy black flake8

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -v

      - name: Run mypy
        run: |
          source .venv/bin/activate
          python -m mypy src

      - name: Run black check
        run: |
          source .venv/bin/activate
          black --check src tests

      - name: Run flake8
        run: |
          source .venv/bin/activate
          flake8 src tests
